/* global */
/* Sample data for the Admin Dashboard — 2026 cycle.
   3 batches · 47 scholars · 3 trainers.
   Mirrors the current TVI-CAMS Figma modal and batch-card state.
*/

const BATCHES = [
  {
    id: 'BAT-1',
    name: 'AKB Technical — TWSP Batch 2026',
    qualification: 'Animal Production (Chicken Poultry) NC II',
    program: 'TWSP',
    ncLevel: 'NC II',
    trainer: 'Archelyn Satur Gagula',
    scholars: 15,
    approvedSeats: 15,
    trainingStart: 'May 6',
    trainingEnd: 'Jun 13, 2026',
    currentDay: 28,
    totalDays: 39,
    progressPct: 72,
    ntpLag: 8,
    tipDate: 'May 6',
    billingDeadline: 'Jun 23, 2026',
    daysToBilling: 21,
    bsrs: false,
    aouDate: 'Apr 9',
    ntpDate: 'Apr 28',
    reportDate: 'May 11',
    completers: 0,
    dropouts: 0,
    trainingDaySchedule: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    trainingDays: '7×/wk',
    remark: 'Training ongoing — Day 28 of 39.',
    notes: '',
    status: 'ongoing',
    lifecycle: [
      { key: 'aou',    label: 'AOU',      status: 'done',    date: 'Apr 9' },
      { key: 'ntp',    label: 'NTP',      status: 'done',    date: 'Apr 28' },
      { key: 'tip',    label: 'TIP',      status: 'done',    date: 'May 6' },
      { key: 'train',  label: 'TRAINING', status: 'active',  date: 'May 6 – Jun 13' },
      { key: 'entre',  label: 'ENTRE',    status: 'pending', date: 'Jun 14 – Jun 16' },
      { key: 'assess', label: 'ASSESS',   status: 'pending', date: 'Pending' },
      { key: 'bill',   label: 'BILLING',  status: 'pending', date: 'By Jun 23' },
    ],
  },
  {
    id: 'BAT-2',
    name: 'J3ed Farm — CFSP Batch 2026',
    qualification: 'Agricultural Crops Production NC II',
    program: 'CFSP',
    ncLevel: 'NC II',
    trainer: 'Julius R. Maravilla',
    scholars: 15,
    approvedSeats: 15,
    trainingStart: 'Apr 30',
    trainingEnd: 'Jun 10, 2026',
    currentDay: 34,
    totalDays: 42,
    progressPct: 81,
    ntpLag: 0,
    tipDate: 'Apr 30',
    billingDeadline: 'Jun 20, 2026',
    daysToBilling: 18,
    bsrs: true,
    aouDate: 'Apr 9',
    ntpDate: 'Apr 30',
    reportDate: 'May 7',
    completers: 0,
    dropouts: 0,
    trainingDaySchedule: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    trainingDays: '7×/wk',
    remark: 'Training ongoing — Day 34 of 42.',
    notes: 'BSRS approved — coordinate with cooperative head for billing submission.',
    status: 'ongoing',
    lifecycle: [
      { key: 'aou',    label: 'AOU',      status: 'done',    date: 'Apr 9' },
      { key: 'ntp',    label: 'NTP',      status: 'done',    date: 'Apr 30' },
      { key: 'tip',    label: 'TIP',      status: 'done',    date: 'Apr 30' },
      { key: 'train',  label: 'TRAINING', status: 'active',  date: 'Apr 30 – Jun 10' },
      { key: 'entre',  label: 'ENTRE',    status: 'pending', date: 'Jun 11 – Jun 13' },
      { key: 'assess', label: 'ASSESS',   status: 'pending', date: 'Pending' },
      { key: 'bill',   label: 'BILLING',  status: 'pending', date: 'By Jun 20' },
    ],
  },
  {
    id: 'BAT-3',
    name: 'Nenita Farm Rice-Based Farm — CFSP Batch 2026',
    qualification: 'Agricultural Crops Production NC II',
    program: 'CFSP',
    ncLevel: 'NC II',
    trainer: 'Agustin A. Pudadera III',
    scholars: 17,
    approvedSeats: 17,
    trainingStart: 'Apr 21',
    trainingEnd: 'Jun 8, 2026',
    currentDay: 37,
    totalDays: 42,
    progressPct: 88,
    ntpLag: 6,
    tipDate: 'Apr 21',
    billingDeadline: 'Jun 18, 2026',
    daysToBilling: 16,
    bsrs: true,
    aouDate: 'Apr 13',
    ntpDate: 'Apr 15',
    reportDate: 'Apr 22',
    completers: 0,
    dropouts: 0,
    trainingDaySchedule: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    trainingDays: '6×/wk',
    remark: 'Training ongoing — Day 37 of 42. Nearing completion.',
    notes: 'Training completing soon. Begin preparing billing documents now.',
    status: 'ongoing',
    lifecycle: [
      { key: 'aou',    label: 'AOU',      status: 'done',    date: 'Apr 13' },
      { key: 'ntp',    label: 'NTP',      status: 'done',    date: 'Apr 15' },
      { key: 'tip',    label: 'TIP',      status: 'done',    date: 'Apr 21' },
      { key: 'train',  label: 'TRAINING', status: 'active',  date: 'Apr 21 – Jun 8' },
      { key: 'entre',  label: 'ENTRE',    status: 'pending', date: 'Jun 9 – Jun 11' },
      { key: 'assess', label: 'ASSESS',   status: 'pending', date: 'Pending' },
      { key: 'bill',   label: 'BILLING',  status: 'pending', date: 'By Jun 18' },
    ],
  },
];

const ACTIVITY = [
  { id: 'a1', when: 'today · 14:02', tone: 'green', who: 'Coordinator', text: 'BSRS approval received for BAT-2 J3ed Farm. Eligible for billing submission.' },
  { id: 'a2', when: 'today · 11:18', tone: 'blue',  who: 'System',      text: 'Re-synced 3 batches from Notion. Schedule-aware progress recalculated for Jun 2, 2026.' },
  { id: 'a3', when: 'yesterday',     tone: 'green', who: 'Coordinator', text: 'Marked TIP conducted for BAT-3 Nenita Farm.' },
  { id: 'a4', when: 'yesterday',     tone: 'amber', who: 'System',      text: 'ENTRE stage inserted between Training and Assessment for all active batches.' },
  { id: 'a5', when: '2 days ago',    tone: 'green', who: 'A. Gagula',   text: 'Updated scholar attendance for BAT-1 Day 27.' },
  { id: 'a6', when: '3 days ago',    tone: 'blue',  who: 'Coordinator', text: 'Exported audit report — Q2 2026 (3 batches, 47 scholars).' },
  { id: 'a7', when: '4 days ago',    tone: 'red',   who: 'System',      text: 'NTP-to-Start lag exceeded 7 days for BAT-1. Flagged for review.' },
];

window.BATCHES = BATCHES;
window.ACTIVITY = ACTIVITY;
