/* global */
/* Sample data for the Admin Dashboard — 2026 cycle.
   3 batches · 47 scholars · 3 trainers.
   Mirrors examples from the design-system spec.
*/

const BATCHES = [
  {
    id: 'BAT-1',
    name: 'AKB Technical Institute · Batch 1',
    qualification: 'Cookery NC II',
    program: 'TWSP',
    ncLevel: 'NC II',
    trainer: 'Archelyn Gagula',
    scholars: 15,
    trainingDays: 'weekdays',
    trainingStart: 'Apr 21',
    trainingEnd: 'Jun 8, 2026',
    duration: 42,
    currentDay: 31,
    totalDays: 42,
    progressPct: 74,
    ntpLag: 7,
    tipDate: 'Apr 21',
    billingDeadline: 'Jun 18, 2026',
    daysToBilling: 3,
    bsrs: true,
    remark: 'Training ongoing — Day 31 of 42. Earliest billing deadline.',
    status: 'ongoing',
    lifecycle: [
      { key: 'aou',    label: 'AOU',      status: 'done',    date: 'Apr 9' },
      { key: 'ntp',    label: 'NTP',      status: 'done',    date: 'Apr 15' },
      { key: 'tip',    label: 'TIP',      status: 'done',    date: 'Apr 21' },
      { key: 'train',  label: 'TRAINING', status: 'active',  date: 'Apr 21 – Jun 8' },
      { key: 'assess', label: 'ASSESS',   status: 'pending', date: 'Pending' },
      { key: 'bill',   label: 'BILLING',  status: 'pending', date: 'By Jun 18' },
    ],
  },
  {
    id: 'BAT-2',
    name: 'J3ed Farm Cooperative · Batch 2',
    qualification: 'Agri Crops Production NC I',
    program: 'CFSP',
    ncLevel: 'NC I',
    trainer: 'Julius Maravilla',
    scholars: 15,
    trainingDays: 'Mon · Wed · Fri',
    trainingStart: 'Apr 28',
    trainingEnd: 'Jun 22, 2026',
    duration: 38,
    currentDay: 20,
    totalDays: 38,
    progressPct: 53,
    ntpLag: 0,
    tipDate: 'Apr 28',
    billingDeadline: 'Jul 1, 2026',
    daysToBilling: 14,
    bsrs: false,
    remark: 'Training ongoing. BSRS not yet approved — coordinate with cooperative head.',
    status: 'ongoing',
    lifecycle: [
      { key: 'aou',    label: 'AOU',      status: 'done',    date: 'Apr 12' },
      { key: 'ntp',    label: 'NTP',      status: 'done',    date: 'Apr 28' },
      { key: 'tip',    label: 'TIP',      status: 'done',    date: 'Apr 28' },
      { key: 'train',  label: 'TRAINING', status: 'active',  date: 'Apr 28 – Jun 22' },
      { key: 'assess', label: 'ASSESS',   status: 'pending', date: 'Pending' },
      { key: 'bill',   label: 'BILLING',  status: 'pending', date: 'By Jul 1' },
    ],
  },
  {
    id: 'BAT-3',
    name: 'Nenita Farm Operations · Batch 3',
    qualification: 'Animal Production NC II',
    program: 'CFSP',
    ncLevel: 'NC II',
    trainer: 'Agustin Pudadera III',
    scholars: 17,
    trainingDays: 'weekdays',
    trainingStart: 'May 5',
    trainingEnd: 'Jul 10, 2026',
    duration: 47,
    currentDay: 13,
    totalDays: 47,
    progressPct: 28,
    ntpLag: 5,
    tipDate: 'May 5',
    billingDeadline: 'Jul 18, 2026',
    daysToBilling: 28,
    bsrs: true,
    remark: 'Early training phase. BSRS approved last week.',
    status: 'ongoing',
    lifecycle: [
      { key: 'aou',    label: 'AOU',      status: 'done',    date: 'Apr 18' },
      { key: 'ntp',    label: 'NTP',      status: 'done',    date: 'Apr 30' },
      { key: 'tip',    label: 'TIP',      status: 'done',    date: 'May 5' },
      { key: 'train',  label: 'TRAINING', status: 'active',  date: 'May 5 – Jul 10' },
      { key: 'assess', label: 'ASSESS',   status: 'pending', date: 'Pending' },
      { key: 'bill',   label: 'BILLING',  status: 'pending', date: 'By Jul 18' },
    ],
  },
];

const ACTIVITY = [
  { id: 'a1', when: 'today · 14:02', tone: 'green', who: 'Coordinator', text: 'BSRS approval received for BAT-2 J3ed Farm. Eligible for billing submission.' },
  { id: 'a2', when: 'today · 11:18', tone: 'blue',  who: 'System',      text: 'Re-synced 3 batches from Notion. No structural changes.' },
  { id: 'a3', when: 'yesterday',     tone: 'green', who: 'Coordinator', text: 'Marked TIP conducted for BAT-3 Nenita Farm.' },
  { id: 'a4', when: 'yesterday',     tone: 'amber', who: 'System',      text: 'BAT-1 entered <7 day billing window. Surfaced at top of dashboard.' },
  { id: 'a5', when: '2 days ago',    tone: 'green', who: 'A. Gagula',   text: 'Updated scholar attendance for BAT-1 Day 30.' },
  { id: 'a6', when: '3 days ago',    tone: 'blue',  who: 'Coordinator', text: 'Exported audit report — Q2 2026 (3 batches, 47 scholars).' },
  { id: 'a7', when: '4 days ago',    tone: 'red',   who: 'System',      text: 'NTP-to-Start lag exceeded 7 days for BAT-1. Flagged for review.' },
];

window.BATCHES = BATCHES;
window.ACTIVITY = ACTIVITY;
